---
apiVersion: v1
kind: Service
metadata:
  name: conference-service
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: conferences
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conferences-deployment
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: conferences
  replicas: 1
  template:
    metadata:
      labels:
        app: conferences
    spec:
      containers:
      - name: conferences
        image: nextgenconf.azurecr.io/nextgenconf/conferenceservice:5fb4bd009016e3ef20485d5f675e74dc60b7a992
        env:
        - name: MONGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: username
        - name: MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: password
        - name: MONGO_DB_PORT
          value: '10255'
        - name: MONGO_DB_PARAMETERS
          value: ssl=true&replicaSet=globaldb
        - name: MONGO_DB_HOST
          value: nextgenconf.documents.azure.com

        ports:
        - containerPort: 5000
