---
apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: web-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: nextgenconf.azurecr.io/nextgenconf/webapp:a3346002860d017b8d87586d491cc08274d9dde9
        ports:
        - containerPort: 80
