---
apiVersion: v1
kind: Service
metadata:
  name: session-service
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: sessions
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sessions-deployment
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: sessions
  replicas: 1
  template:
    metadata:
      labels:
        app: sessions
    spec:
      containers:
      - name: sessions
        image: nextgenconf.azurecr.io/nextgenconf/sessionservice:8cae59cb951c7668bf937e2177203ca6d306b06d
        env:
        - name: MONGO_DB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: username
        - name: MONGO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: password
        - name: MONGO_DB_PORT
          value: '10255'
        - name: MONGO_DB_PARAMETERS
          value: ssl=true&replicaSet=globaldb
        - name: MONGO_DB_HOST
          value: nextgenconf.documents.azure.com

        ports:
        - containerPort: 5000
