apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBFXM3kFcOy9T4Sdhhz05tLagdXQuylvpZCM90TbdhPUD2qYoRARsdVwaM/QVO82pUxbX50QaE7tJMkW99WVXmu/l75ip+ay7Pa1ljAdNt1CLwVvP9ApJrE/Ng2FdZHnmGvox9LPoitPuhQZUpm+W9WSK/EiCBpqamlXV3/KWeJzJvkPpgOZarX+DQOBYEnPKt5SUtbbEd2E+g+sszQHan32bZh+5iPBFp+z6FQBp3/jGoY2ZLS9htIRm3PiObQnsyINhzIkVB1wr7m4rYyBdOGkDG0pgnrlRtqSMUiZLJ6LFk9qhYISPHO3hJJPD+VFtLrD5YoUyxDY+JTaljcMO+rj18t5ZTb/xgk6H1urgf4f3r+lysHB2rhB+UP5Z7/Tjqlkvej63msrCZFn03BL7JSVVrd1kxgx5+cyKlK9WVN0M37puX9FXn0qdbuMz2Hb/x5NMRe1q0FP9JFTQPiq4wCbl6CPe/OUUMrHr1OJQEFyoWIVM9bI+5wLUr0TCCahovi9GK/NWytq+UleHlYotMAZr7CXr3LVkFFCRJ+aBos75ceLTnLjpUdbGiP2Iq6+5j79uFfvKY6EhMwkAW5jkwP2Xsa40Bc1pCQ1/tpWhetlRVmf2OSrjpy+Ci9sTjOsJcUnV9wc7adf68lyShQMqmiX+2s+JIG3CIRM0wG+tRkJA+pQl6fKXgy4P3xRrTDdyEURvqIhNfTufYV+wT2ema+rHG46hDsxhr9owq2BlRTZwctqa5RGcK5nkmEkvUdettcsuszt5qivAmy4IcQulGnKAu6p7J9Zd6BoQr0v/l7GrG0UHSNt3JR
    username: AgAGODN+HIDKyYxJ4xlcOmYpQQw+n1ElPVESwFkCKalPuLrjv3EfepUCHoIgfKDUNtVA+DogGkC4IhSfOYHr5aTc3Fb+W6dlXyRbPn5Fog1ajM9SCbQcmS1ouQPwGwLPiuRTS4tQaoj0bfkXs6jqYaEnvknLyjZ8Qh00d5Fz0xdDh/jgocsU4iEH2tsKg71EVyaF221qnZTIg20FD9M1+Hay9dNBNNFyiXbV02iMaIt8VGzYbEHuDKfjNH7m63VqB763CTKRHaWor0QHlWY3HXnZsRIlXn9tGlMBBeixfB3OYmy9/Dh7OQf6RsmvkntnVLlw4m6TjWrQQ23RwX+nsQkXHSpvcl9y7c+L5YQn/PQ5jhzue/ohJJ87/twrZFmGFMFjWUx5WM32ZnLGJGUNQ53BItXrkUjo7ysWpbrMrzR+ciyUbA/kEz/gs6M8Z+Yq+Vay1MPJ1qoQMbJbiKMpc+YvqQgRXOC+vXNL1o8UW2nB5GbYwKUT8cCzs06SDPf1C67bYly5AImZeh+xCS6gb70QCaqif9jqozDt+twQr3fQdRq7r5UVi0E1D559kn/7GYykxHTFU+dB/viv3zgAbCqdSTm4rWij7eM4A5gKwAa8OSjiLlr3pLgfEFpnXR7O0t0fIvNfSB5ZiGR+MP+zzimuFP051tKM5a3bsbf32YFy2cTNAis1Yc25wDCM4EOyoR4tQ1PZfQYZ/Lg96Q==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-credentials
      namespace: default
status: {}

