---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: sessions
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sessions-deployment
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: sessions
  replicas: 1
  template:
    metadata:
      labels:
        app: sessions
    spec:
      containers:
      - name: sessions
        image: nextgenconf.azurecr.io/nextgenconf/apigateway:c5c6ea162a3f829d7cbcd8ff8c45714c7873d260
        env:
        - name: CONFERENCES_BASE_URL
          value: 'http://conference-service:80'
        env:
        - name: SESSIONS_BASE_URL
          value: 'http://session-service:80'

        ports:
        - containerPort: 4000
